filebeat:
  image: docker.elastic.co/beats/filebeat:6.2.4
  privileged: false
  restart: always
  volumes:
  - config/filebeat.yml:/usr/share/filebeat/filebeat.yml
  - /tmp:/tmp #/opt/log/filebeat为本机物理地址
  environment:
  - TZ=Asia/Shanghai