setup.template.name: "filebeat_log"
setup.template.pattern: "merit_log-*"
setup.template.enabled: true
filebeat.prospectors:
- type: log
  fields:
    type: "filebeat"
  tags: ["filebeat"]
  encoding: utf-8
  scan_frequency: 10s
  force_close_files: true
  paths:
    - /tmp/*.log    # /filebeat为docker-compose映射路径
  multiline.pattern: '^[0-9]{4}-[0-9]{2}-[0-9]{2}'
  multiline.negate: true
  multiline.match: after
output.elasticsearch:
  hosts: ["192.168.3.235:5044"]
  index: "merit_test_log-%{+yyyy.MM.dd}"