version: '3.6'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - config/elasticsearch.yml:/usr/share/elasticsearch/data/elasticsearch.yml
    ports:
      - "9200:9200"
    networks:
      - esnet
    deploy:
      placement:
        constraints:
          - node.role == manager

  elasticsearch2:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=elasticsearch"
    volumes:
      - config/elasticsearch2.yml:/usr/share/elasticsearch/data/elasticsearch.yml
    networks:
      - esnet
    deploy:
      placement:
        constraints:
          - node.role == worker

  logstash:
    image: docker.elastic.co/logstash/logstash:6.2.4
    environment:
      - "LS_JAVA_OPTS=-Xms256m -Xmx256m"
    ports:
      - "5044:5044"
    networks:
      - esnet
    deploy:
      placement:
        constraints:
          - node.role == manager

  filebeat:
    image: docker.elastic.co/beats/filebeat:6.2.4
    volumes:
      - config/filebeat.yml:/usr/share/filebeat/data/filebeat.yml
      - /tmp:/tmp #/opt/log/filebeat为本机物理地址
    environment:
      - TZ=Asia/Shanghai
    networks:
      - esnet
    deploy:
      placement:
        constraints:
          - node.role == manager

  filebeat2:
    image: docker.elastic.co/beats/filebeat:6.2.4
    volumes:
      - config/filebeat.yml:/usr/share/filebeat/data/filebeat.yml
      - /tmp:/tmp #/opt/log/filebeat为本机物理地址
    environment:
      - TZ=Asia/Shanghai
    networks:
      - esnet
    deploy:
      placement:
        constraints:
          - node.role == worker

  kibana:
    image: docker.elastic.co/kibana/kibana:6.2.4
    ports:
      - "5601:5601"
    networks:
      - esnet
    deploy:
      placement:
        constraints:
          - node.role == manager
#volumes:
#  esdata1:
#    driver: local
#  esdata2:
#    driver: local

networks:
  esnet:
    driver: "overlay"