version: '3.6'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4
    environment:
      - bootstrap.memory_lock=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elastic
    deploy:
      placement:
        constraints:
          - node.role == manager

  logstash:
    image: docker.elastic.co/logstash/logstash:6.2.4
    environment:
      - "LS_JAVA_OPTS=-Xms256m -Xmx256m"
    networks:
      - elastic
    volumes:
      - ./config/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - logstash:/usr/share/logstash/data
      - /tmp:/tmp
    deploy:
      placement:
        constraints:
          - node.role == manager

  logstash1:
    image: docker.elastic.co/logstash/logstash:6.2.4
    environment:
      - "LS_JAVA_OPTS=-Xms256m -Xmx256m"
    networks:
      - elastic
    volumes:
      - ./config/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - logstash1:/usr/share/logstash/data
      - /tmp:/tmp
    deploy:
      placement:
        constraints:
          - node.role == worker

  kibana:
    image: docker.elastic.co/kibana/kibana:6.2.4
    volumes:
      - ./config/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - "5601:5601"
    networks:
      - elastic
    deploy:
      placement:
        constraints:
          - node.role == manager

volumes:
  esdata:
    driver: local
  logstash:
    driver: local
  logstash1:
    driver: local

networks:
  elastic:
    driver: "overlay"
